apiVersion: batch/v1
kind: Job
metadata:
  name: prestart
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prestart
          image: TON_IMAGE_BACKEND:latest
          command:
            - bash
            - scripts/prestart.sh